name: deploy

on:
  push:
    branches:
      - adding-workflows

env:
  AWS_REGION: 'us-east-1'
  IMAGE_NAME: 'test-image'
  IMAGE_VERSION: 'latest'

jobs:
  continuous-deployment:    
    runs-on: ubuntu-latest
    steps:
      - name: Install AWS CLI        
        uses: unfor19/install-aws-cli-action@v1        
        with:          
          version: 1        
        env:          
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}          
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}          
          aws-region: ${{ env.AWS_REGION }}       
      - name: Configure AWS credentials        
        uses: aws-actions/configure-aws-credentials@v1        
        with:          
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}                
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}          
          aws-region: ${{ env.AWS_REGION }}       
      - name: Login to Amazon ECR        
        id: login-ecr        
        uses: aws-actions/amazon-ecr-login@v1            
      - name: Check out code        
        uses: actions/checkout@v2          
      - name: Create docker images        
        run: docker build -t 240833302201.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}      
      - name: Upload docker into ECR        
        run: docker push 240833302201.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_NAME }}:${{ env.IMAGE_VERSION }}   